# Screen Config
SCREEN_HEIGHT = 600
SCREEN_WIDTH = 800
SCREEN_COLOR_MODE = 255
SCREEN_COLOR = (230, 230, 230)
SCREEN_REFRESH_TIME = 0.3

# Player Config
PLAYER_WIDTH = 20
PLAYER_SHAPE = "turtle"
PLAYER_SPEED = "fastest"
PLAYER_COLOR = (0, 0, 0)
PLAYER_INIT_X_POS = 0
PLAYER_Y_DIST_TO_WALL = 20
PLAYER_HEADING = 90
PLAYER_MOVE_DISTANCE = 20
PLAYER_LEVEL_CAR_SPEED_DIVISOR = 1

# Car Config
CAR_SPEED = "fastest"
CAR_STRETCH_LEN = 2
CAR_STRETCH_WIDTH = 1
CAR_SHAPE = "square"
CAR_WIDTH = 40
CAR_MOVEMENT_SPEED = 10
SLEEP_TIME_DECREASE_WHEN_FINISH = 0.5

# Score Board Config
SCOREBOARD_COLOR = (0, 0, 0)
SCOREBOARD_TEXT_FONT = "Courier"
SCOREBOARD_TEXT_SIZE = 24
SCOREBOARD_TEXT_STYLE = "normal"
SCOREBOARD_TEXT_ALIGN = "center"
GAME_OVER_TEXT = "GAME OVER"
GAME_OVER_TEXT_FONT = "Courier"
GAME_OVER_TEXT_SIZE = 40
GAME_OVER_TEXT_STYLE = "bold"
GAME_OVER_TEXT_ALIGN = "center"
